version: '3'

services:
  aws-manager:
    image: roribio16/alpine-sqs:latest
    container_name: aws-manager
    ports:
      - "9324:9324"
      - "9325:9325"
    stdin_open: true
    tty: true
    volumes:
    - ./custom/custom.conf:/opt/custom/elasticmq.conf
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"